"""Initial schema with sessions, questions, and api_keys tables

Revision ID: c28865ecbb00
Revises: 
Create Date: 2025-12-03 17:22:00.700118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28865ecbb00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_is_answered'), 'questions', ['is_answered'], unique=False)
    op.create_index('ix_questions_session_answered', 'questions', ['session_id', 'is_answered'], unique=False)
    op.create_index(op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False)
    op.create_index('ix_questions_session_id_question_number', 'questions', ['session_id', 'question_number'], unique=False)
    op.create_index('ix_questions_session_upvotes', 'questions', ['session_id', 'upvotes'], unique=False)
    op.create_index(op.f('ix_questions_upvotes'), 'questions', ['upvotes'], unique=False)
    op.create_unique_constraint('uq_session_question_number', 'questions', ['session_id', 'question_number'])
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_constraint('uq_session_question_number', 'questions', type_='unique')
    op.drop_index(op.f('ix_questions_upvotes'), table_name='questions')
    op.drop_index('ix_questions_session_upvotes', table_name='questions')
    op.drop_index('ix_questions_session_id_question_number', table_name='questions')
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_index('ix_questions_session_answered', table_name='questions')
    op.drop_index(op.f('ix_questions_is_answered'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    # ### end Alembic commands ###
