"""Add v2 schema: instructor, class, class_meeting, answer, question_vote tables

Revision ID: c6671aaf91d2
Revises: c28865ecbb00
Create Date: 2025-12-03 17:28:04.341382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6671aaf91d2'
down_revision: Union[str, None] = None  # First migration - fresh start with v2
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructors_created_at'), 'instructors', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructors_email'), 'instructors', ['email'], unique=True)
    op.create_index(op.f('ix_instructors_id'), 'instructors', ['id'], unique=False)
    op.create_index(op.f('ix_instructors_is_active'), 'instructors', ['is_active'], unique=False)
    op.create_index(op.f('ix_instructors_username'), 'instructors', ['username'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_created_at'), 'classes', ['created_at'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index('ix_classes_instructor_archived', 'classes', ['instructor_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_classes_instructor_id'), 'classes', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_classes_is_archived'), 'classes', ['is_archived'], unique=False)
    op.create_table('class_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('meeting_code', sa.String(), nullable=False),
    sa.Column('instructor_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_meetings_api_key_id'), 'class_meetings', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_class_meetings_class_id'), 'class_meetings', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_meetings_created_at'), 'class_meetings', ['created_at'], unique=False)
    op.create_index(op.f('ix_class_meetings_id'), 'class_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_class_meetings_instructor_code'), 'class_meetings', ['instructor_code'], unique=True)
    op.create_index(op.f('ix_class_meetings_is_active'), 'class_meetings', ['is_active'], unique=False)
    op.create_index(op.f('ix_class_meetings_meeting_code'), 'class_meetings', ['meeting_code'], unique=True)
    op.create_index('ix_meetings_class_active', 'class_meetings', ['class_id', 'is_active'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_created_at'), 'answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_index('ix_answers_instructor_approved', 'answers', ['instructor_id', 'is_approved'], unique=False)
    op.create_index(op.f('ix_answers_instructor_id'), 'answers', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_answers_is_approved'), 'answers', ['is_approved'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=True)
    op.create_table('question_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'student_id', name='uq_question_student_vote')
    )
    op.create_index(op.f('ix_question_votes_created_at'), 'question_votes', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_votes_id'), 'question_votes', ['id'], unique=False)
    op.create_index(op.f('ix_question_votes_question_id'), 'question_votes', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_votes_student_id'), 'question_votes', ['student_id'], unique=False)
    op.create_index('ix_votes_student', 'question_votes', ['student_id', 'created_at'], unique=False)
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_index('ix_sessions_instructor_code', table_name='sessions')
    op.drop_index('ix_sessions_session_code', table_name='sessions')
    op.drop_table('sessions')
    op.add_column('api_keys', sa.Column('instructor_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_instructor_id'), 'api_keys', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'instructors', ['instructor_id'], ['id'], ondelete='CASCADE')
    op.add_column('questions', sa.Column('meeting_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('student_id', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('sanitized_text', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('flagged_reason', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('is_answered_in_class', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('has_written_answer', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_has_written_answer'), 'questions', ['has_written_answer'], unique=False)
    op.create_index(op.f('ix_questions_is_answered_in_class'), 'questions', ['is_answered_in_class'], unique=False)
    op.create_index(op.f('ix_questions_meeting_id'), 'questions', ['meeting_id'], unique=False)
    op.create_index('ix_questions_meeting_question_number', 'questions', ['meeting_id', 'question_number'], unique=False)
    op.create_index('ix_questions_meeting_status', 'questions', ['meeting_id', 'status'], unique=False)
    op.create_index('ix_questions_meeting_upvotes', 'questions', ['meeting_id', 'upvotes'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index('ix_questions_student', 'questions', ['student_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_questions_student_id'), 'questions', ['student_id'], unique=False)
    op.create_index(op.f('ix_questions_upvotes'), 'questions', ['upvotes'], unique=False)
    op.create_unique_constraint('uq_meeting_question_number', 'questions', ['meeting_id', 'question_number'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'class_meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'session_id')
    op.drop_column('questions', 'is_answered')
    op.drop_column('questions', 'answered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answered_at', sa.DATETIME(), nullable=True))
    op.add_column('questions', sa.Column('is_answered', sa.BOOLEAN(), nullable=True))
    op.add_column('questions', sa.Column('session_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'sessions', ['session_id'], ['id'])
    op.drop_constraint('uq_meeting_question_number', 'questions', type_='unique')
    op.drop_index(op.f('ix_questions_upvotes'), table_name='questions')
    op.drop_index(op.f('ix_questions_student_id'), table_name='questions')
    op.drop_index('ix_questions_student', table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index('ix_questions_meeting_upvotes', table_name='questions')
    op.drop_index('ix_questions_meeting_status', table_name='questions')
    op.drop_index('ix_questions_meeting_question_number', table_name='questions')
    op.drop_index(op.f('ix_questions_meeting_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_answered_in_class'), table_name='questions')
    op.drop_index(op.f('ix_questions_has_written_answer'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_column('questions', 'reviewed_at')
    op.drop_column('questions', 'has_written_answer')
    op.drop_column('questions', 'is_answered_in_class')
    op.drop_column('questions', 'flagged_reason')
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'sanitized_text')
    op.drop_column('questions', 'student_id')
    op.drop_column('questions', 'meeting_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_instructor_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_column('api_keys', 'instructor_id')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_code', sa.VARCHAR(), nullable=False),
    sa.Column('instructor_code', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_session_code', 'sessions', ['session_code'], unique=1)
    op.create_index('ix_sessions_instructor_code', 'sessions', ['instructor_code'], unique=1)
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    op.drop_index('ix_votes_student', table_name='question_votes')
    op.drop_index(op.f('ix_question_votes_student_id'), table_name='question_votes')
    op.drop_index(op.f('ix_question_votes_question_id'), table_name='question_votes')
    op.drop_index(op.f('ix_question_votes_id'), table_name='question_votes')
    op.drop_index(op.f('ix_question_votes_created_at'), table_name='question_votes')
    op.drop_table('question_votes')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_is_approved'), table_name='answers')
    op.drop_index(op.f('ix_answers_instructor_id'), table_name='answers')
    op.drop_index('ix_answers_instructor_approved', table_name='answers')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_created_at'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_meetings_class_active', table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_meeting_code'), table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_is_active'), table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_instructor_code'), table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_id'), table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_created_at'), table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_class_id'), table_name='class_meetings')
    op.drop_index(op.f('ix_class_meetings_api_key_id'), table_name='class_meetings')
    op.drop_table('class_meetings')
    op.drop_index(op.f('ix_classes_is_archived'), table_name='classes')
    op.drop_index(op.f('ix_classes_instructor_id'), table_name='classes')
    op.drop_index('ix_classes_instructor_archived', table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_created_at'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_instructors_username'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_is_active'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_id'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_email'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_created_at'), table_name='instructors')
    op.drop_table('instructors')
    # ### end Alembic commands ###
