#!/usr/bin/env python3
"""
Setup production environment for RaiseMyHand

This script generates .env.production with proper configuration:
  - Random SECRET_KEY and CSRF_SECRET
  - Prompts for critical passwords and configuration
  - Validates inputs before writing

Usage:
  python scripts/setup_production.py

Or in Docker:
  docker compose -f docker-compose.prod.yml run --rm app python scripts/setup_production.py
"""
import os
import sys
import secrets
import re
from pathlib import Path


def validate_password(password: str, min_length: int = 12) -> bool:
    """Validate password strength."""
    return len(password) >= min_length


def validate_url(url: str) -> bool:
    """Validate URL format."""
    url_pattern = re.compile(
        r'^https?://'  # http:// or https://
        r'(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}|'  # domain
        r'localhost|'  # localhost
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'  # IP address
        r'(?::\d+)?'  # optional port
        r'$'
    )
    return bool(url_pattern.match(url))


def generate_secret() -> str:
    """Generate a random 32+ character secret."""
    return secrets.token_urlsafe(32)


def prompt_user(prompt: str, default: str = None, validate_func=None, required: bool = True) -> str:
    """Prompt user for input with optional validation."""
    while True:
        if default:
            display_prompt = f"{prompt} [{default}]: "
        else:
            display_prompt = f"{prompt}: "

        value = input(display_prompt).strip()

        # Use default if empty and default exists
        if not value and default:
            value = default

        # Validate required fields
        if required and not value:
            print("   ❌ This field is required\n")
            continue

        # Validate with custom function if provided
        if validate_func and value:
            if not validate_func(value):
                print(f"   ❌ Invalid input\n")
                continue

        return value


def main():
    print("\n" + "=" * 70)
    print("🚀 RaiseMyHand Production Setup".center(70))
    print("=" * 70)

    # Check if .env.production already exists
    env_prod_path = Path(".env.production")
    if env_prod_path.exists():
        response = input("\n⚠️  .env.production already exists. Overwrite? (y/n): ").strip().lower()
        if response != "y":
            print("Cancelled.")
            return

    print("\n📋 Configuration Setup")
    print("-" * 70)

    # Database Configuration
    print("\n🗄️  Database Configuration")
    postgres_user = prompt_user("  PostgreSQL User", default="raisemyhand")
    postgres_password = prompt_user(
        "  PostgreSQL Password (min 16 chars)",
        validate_func=lambda x: validate_password(x, min_length=16),
        required=True
    )
    postgres_db = prompt_user("  PostgreSQL Database Name", default="raisemyhand")

    # Server Configuration
    print("\n🌐 Server Configuration")
    base_url = prompt_user(
        "  Base URL (e.g., https://questions.yourschool.edu)",
        validate_func=validate_url,
        required=True
    )

    # Security Configuration
    print("\n🔐 Security Configuration")
    print("  → Generating random secrets...")
    secret_key = generate_secret()
    csrf_secret = generate_secret()
    print(f"    ✓ SECRET_KEY: {secret_key[:20]}...")
    print(f"    ✓ CSRF_SECRET: {csrf_secret[:20]}...")

    admin_password = prompt_user(
        "  Admin Password (min 12 chars)",
        validate_func=lambda x: validate_password(x, min_length=12),
        required=True
    )
    admin_username = prompt_user("  Admin Username", default="admin")

    # Optional: Timezone
    print("\n🕐 Optional Configuration")
    timezone = prompt_user(
        "  Timezone (IANA format)",
        default="America/New_York",
        required=False
    )

    # Generate .env.production content
    env_content = f"""# RaiseMyHand Production Environment Configuration
# Generated by setup_production.py
# DO NOT COMMIT THIS FILE - Add to .gitignore

# Environment Type
ENV=production

# =============================================================================
# Database Configuration - PostgreSQL
# =============================================================================
POSTGRES_USER={postgres_user}
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB={postgres_db}

# =============================================================================
# External Access Configuration
# =============================================================================
BASE_URL={base_url}

# =============================================================================
# Security Configuration
# =============================================================================
SECRET_KEY={secret_key}
CSRF_SECRET={csrf_secret}

ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_password}

# =============================================================================
# Server Configuration
# =============================================================================
HOST=0.0.0.0
PORT=8000
TIMEZONE={timezone}

# =============================================================================
# Production Settings
# =============================================================================
DEBUG=false
DEMO_MODE=false
ENABLE_AUTH=true
RATE_LIMIT_ENABLED=true
ACCESS_TOKEN_EXPIRE_MINUTES=480

# =============================================================================
# Optional: PgAdmin Configuration (for database management)
# =============================================================================
# To access: docker compose -f docker-compose.prod.yml --profile management up
PGADMIN_EMAIL=admin@example.com
PGADMIN_PASSWORD=admin
"""

    # Write to file
    try:
        with open(env_prod_path, "w") as f:
            f.write(env_content)

        # Set appropriate permissions (readable only by owner)
        os.chmod(env_prod_path, 0o600)

        print("\n" + "=" * 70)
        print("✅ Production Configuration Created".center(70))
        print("=" * 70)

        print(f"\n📁 Created: {env_prod_path}")
        print(f"🔒 Permissions: 600 (owner read/write only)")

        print("\n📊 Configuration Summary:")
        print(f"   Database: PostgreSQL ({postgres_user}@postgres:5432/{postgres_db})")
        print(f"   Base URL: {base_url}")
        print(f"   Admin User: {admin_username}")
        print(f"   Timezone: {timezone}")

        print("\n🚀 Next Steps:")
        print("   1. Review .env.production for any needed adjustments")
        print("   2. Start production environment:")
        print("      docker compose -f docker-compose.prod.yml up -d")
        print("   3. Check deployment:")
        print("      docker logs raisemyhand-app")
        print("   4. Access the application at: " + base_url)

        print("\n💾 IMPORTANT SECURITY NOTES:")
        print("   ✓ Ensure .env.production is in .gitignore")
        print("   ✓ Back up .env.production in a secure location")
        print("   ✓ Use strong passwords (already set above)")
        print("   ✓ Configure SSL/TLS via nginx reverse proxy")
        print("   ✓ Restrict database port 5432 to trusted hosts only")
        print("   ✓ Set up automated backups for PostgreSQL")

        print("\n" + "=" * 70 + "\n")

    except Exception as e:
        print(f"\n❌ Error creating .env.production: {e}")
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)
